version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/
          paths:
            - .
  deploy: # this can be any name you choose
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

# workflows:
#   test_my_app:
#     jobs:
#       - build_and_test
#       - deploy:
#           requires:
#             - build_and_test # only deploy if the build_and_test job has completed
#           filters:
#             branches:
#               only: main # only deploy when on main
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
jobs:
  build:
    docker:
      - image: cimg/node:15.0.1-browsers
        auth:
          username: brucewayne11062001
          password: Utkarsh@11  # context / project UI env-var reference
    working_directory: ~/circleci-demo-workflows
    # steps:
    #   - checkout
    #   # Bundle install dependencies
    #   - run: bundle install --path vendor/bundle
    #   # Database setup
    #   - run: bundle exec rake db:create db:schema:load
    #   - run:
    #       name: Run tests
    #       command: rake